apiVersion: batch/v1
kind: CronJob
metadata:
  name: call-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: call-job
              image: alpine
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - wget {{ .Values.wget.endpoint }} -S -U {{ .Values.wget.agent }}
          restartPolicy: OnFailure