apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  labels: {{ include "example.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{ include "example.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "example.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "name" . }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html
          configMap:
            name: homepage-html