apiVersion: v1
kind: Service
metadata:
  name: homepage-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector: {{ include "example.labels" . | nindent 4 }}
  type: NodePort
