apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-example
  name: nginx-example
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    run: nginx-example
  type: ClusterIP